export const scenes = {
  TITLE: 'TitleScene',
  HUB: 'HubScene',
  PREP: 'PrepScene',
  TRAVEL: 'TravelScene',
  BATTLE: 'BattleScene',
};

export const palette = {
  dark: 0x160d0a,
  panel: 0x382112,
  brown: 0x6f4a2d,
  leather: 0x2a1710,
  yellow: 0xf0c24f,
  pale: 0xffe6a6,
  white: 0xfff8e7,
  green: 0x65a24f,
  cactus: 0x2f6f3f,
  red: 0xb44732,
  blue: 0x5f9bad,
  shadow: 0x070302,
};

export const weaponCatalog = {
  revolver: {
    id: 'revolver',
    name: 'Revolver',
    range: 5,
    damage: 1,
    description: 'Flexible sidearm. Reliable from Mid lane, fast stances, and tempo builds.',
  },
  shotgun: {
    id: 'shotgun',
    name: 'Shotgun',
    range: 3,
    damage: 5,
    description: 'Short-range scattergun. Strong up close and can tear open Bleeding Out.',
  },
  rifle: {
    id: 'rifle',
    name: 'Rifle',
    range: 7,
    damage: 3,
    description: 'Long gun. Best from Back lane, ridges, and cover.',
  },
  throwable: {
    id: 'throwable',
    name: 'Throwables',
    range: 4,
    damage: 0,
    description: 'Disruptive dynamite and dust bombs. Lower damage, but snares targets and bends tempo.',
  },
  melee: {
    id: 'melee',
    name: 'Melee',
    range: 1,
    damage: 7,
    description: 'Close pressure. Risky reach, high impact, and strong at interrupting mounts.',
  },
};

export const partyTemplate = [
  {
    id: 'marshal',
    side: 'ally',
    name: 'Marshal Vale',
    role: 'Frontier Guardian',
    equippedWeapon: 'shotgun',
    talent: {
      id: 'close-quarters-marshal',
      name: 'Close Quarters Marshal',
      preferredWeapon: 'shotgun',
      description: 'Shotguns tear open Bleeding Out at close range.',
      tags: ['Shotgun', 'Bleed'],
    },
    combatTraits: [
      { name: 'Breacher', tags: ['Shotgun'], description: 'Close hits land heavier.' },
      { name: 'Iron Hide', tags: ['Tank'], description: 'Defensive stances hold longer.' },
      { name: 'Last Stand', tags: ['Grit'], description: 'Grit turns routes into comebacks.' },
    ],
    combatTraitOptions: [
      { name: 'Breacher', tags: ['Shotgun'], description: 'Close hits land heavier.' },
      { name: 'Iron Hide', tags: ['Tank'], description: 'Defensive stances hold longer.' },
      { name: 'Last Stand', tags: ['Grit'], description: 'Grit turns routes into comebacks.' },
      { name: 'Dust Shield', tags: ['Tank'], description: 'Cover and guard choices reduce pressure.' },
      { name: 'Blood Price', tags: ['Bleed'], description: 'Bleeding targets invite harder follow-ups.' },
    ],
    bondTraits: [
      { name: 'Saddle Guard', tags: ['Mounted'], description: 'Bonded mounts protect Vale in front lanes.' },
      { name: 'Steady Reins', tags: ['Panic'], description: 'Horse Panic is easier to recover from.' },
    ],
    bondTraitOptions: [
      { name: 'Saddle Guard', tags: ['Mounted'], description: 'Bonded mounts protect Vale in front lanes.' },
      { name: 'Steady Reins', tags: ['Panic'], description: 'Horse Panic is easier to recover from.' },
      { name: 'Iron Charge', tags: ['Mounted'], description: 'High bond mounted attacks push harder.' },
    ],
    maxHp: 130,
    hp: 130,
    atb: 0,
    horseBonds: { 'brass-hoof': 20 },
    mounted: true,
    horseId: 'brass-hoof',
    riderStance: 'Iron Rider',
    horseStance: 'Defensive Guard',
    skills: [
      {
        id: 'iron-shot',
        name: 'Iron Shot',
        description: 'Heavy revolver shot. Stronger from ridges and can cause Bleeding Out.',
        power: 28,
        target: 'enemy',
        status: 'bleeding-out',
        range: 6,
      },
      {
        id: 'guard-whistle',
        name: 'Guard Whistle',
        description: 'Brace with your horse. Gain Grit.',
        power: 0,
        target: 'self',
        status: 'grit',
      },
      {
        id: 'marshal-mark',
        name: 'Marshal Mark',
        description: 'Mark an enemy for a stronger hit.',
        power: 18,
        target: 'enemy',
        status: 'marked',
        range: 6,
      },
    ],
    grid: { x: 7, y: 1 },
  },
  {
    id: 'quickdraw',
    side: 'ally',
    name: 'June Quick',
    role: 'Dual Revolver Outlaw',
    equippedWeapon: 'revolver',
    talent: {
      id: 'fan-the-hammer',
      name: 'Fan the Hammer',
      preferredWeapon: 'revolver',
      description: 'Mid-lane revolver fire keeps ATB tempo high.',
      tags: ['Revolver', 'Mobility'],
    },
    combatTraits: [
      { name: 'Dust Runner', tags: ['Mobility'], description: 'Fast moves feed aggressive turns.' },
      { name: 'Hot Hand', tags: ['Revolver'], description: 'Repeated shots reward tempo.' },
      { name: 'Wanted Smile', tags: ['Wanted'], description: 'Risky outlaw states hit harder.' },
    ],
    combatTraitOptions: [
      { name: 'Dust Runner', tags: ['Mobility'], description: 'Fast moves feed aggressive turns.' },
      { name: 'Hot Hand', tags: ['Revolver'], description: 'Repeated shots reward tempo.' },
      { name: 'Wanted Smile', tags: ['Wanted'], description: 'Risky outlaw states hit harder.' },
      { name: 'Quick Hands', tags: ['Mobility'], description: 'Light weapons favor faster openings.' },
      { name: 'Duel Spark', tags: ['Duel'], description: 'Showdown turns hit with more force.' },
    ],
    bondTraits: [
      { name: 'Ghost Sprint', tags: ['Mounted'], description: 'Bonded mounts favor fast openings.' },
      { name: 'Ride-By Nerve', tags: ['Duel'], description: 'Showdown pressure comes easier mounted.' },
    ],
    bondTraitOptions: [
      { name: 'Ghost Sprint', tags: ['Mounted'], description: 'Bonded mounts favor fast openings.' },
      { name: 'Ride-By Nerve', tags: ['Duel'], description: 'Showdown pressure comes easier mounted.' },
      { name: 'Loose Reins', tags: ['Mobility'], description: 'Mounted repositioning stays cheap.' },
    ],
    maxHp: 96,
    hp: 96,
    atb: 24,
    horseBonds: { 'ghost-pepper': 34 },
    mounted: true,
    horseId: 'ghost-pepper',
    riderStance: 'Gunslinger',
    horseStance: 'Sprint',
    skills: [
      {
        id: 'fan-fire',
        name: 'Fan Fire',
        description: 'Fast multi-shot burst that leaves targets Dust-Choked.',
        power: 22,
        target: 'enemy',
        atbBonus: 8,
        status: 'dust-choked',
        range: 4,
      },
      {
        id: 'dust-step',
        name: 'Dust Step',
        description: 'Quick reposition stance. Gain Showdown.',
        power: 0,
        target: 'self',
        status: 'showdown',
      },
      {
        id: 'low-health-shot',
        name: 'Desperado',
        description: 'Hits harder when wounded and draws Wanted heat.',
        power: 20,
        target: 'enemy',
        outlawBonus: true,
        selfStatuses: ['wanted', 'whiskey-dazed'],
        range: 5,
      },
    ],
    grid: { x: 7, y: 3 },
  },
  {
    id: 'sawbones',
    side: 'ally',
    name: 'Doc Maribel',
    role: 'Trail Medic',
    equippedWeapon: 'rifle',
    talent: {
      id: 'patient-surgeon',
      name: 'Patient Surgeon',
      preferredWeapon: 'rifle',
      description: 'Rifles from cover or Back lane mark targets.',
      tags: ['Rifle', 'Mark'],
    },
    combatTraits: [
      { name: 'Steady Aim', tags: ['Rifle'], description: 'Cover and Back lanes sharpen shots.' },
      { name: 'Trail Triage', tags: ['Support'], description: 'Healing keeps the weakest rider standing.' },
      { name: 'Calm Under Fire', tags: ['Panic'], description: 'Control tools blunt enemy rushes.' },
    ],
    combatTraitOptions: [
      { name: 'Steady Aim', tags: ['Rifle'], description: 'Cover and Back lanes sharpen shots.' },
      { name: 'Trail Triage', tags: ['Support'], description: 'Healing keeps the weakest rider standing.' },
      { name: 'Calm Under Fire', tags: ['Panic'], description: 'Control tools blunt enemy rushes.' },
      { name: 'Field Surgeon', tags: ['Support'], description: 'Recovery choices preserve crew tempo.' },
      { name: 'Long Watch', tags: ['Rifle'], description: 'Back lane plans mark safer targets.' },
    ],
    bondTraits: [
      { name: 'Trusted Mount', tags: ['Mounted'], description: 'Bonded horses recover panic faster.' },
      { name: 'Dustproof Saddle', tags: ['Support'], description: 'Long rides keep support tempo steady.' },
    ],
    bondTraitOptions: [
      { name: 'Trusted Mount', tags: ['Mounted'], description: 'Bonded horses recover panic faster.' },
      { name: 'Dustproof Saddle', tags: ['Support'], description: 'Long rides keep support tempo steady.' },
      { name: 'Quiet Step', tags: ['Mobility'], description: 'Bonded travel reduces rough reposition costs.' },
    ],
    maxHp: 108,
    hp: 108,
    atb: 8,
    horseBonds: { comet: 18 },
    mounted: true,
    horseId: 'comet',
    riderStance: 'Wrangler',
    horseStance: 'Calm Focus',
    skills: [
      {
        id: 'trail-mend',
        name: 'Trail Mend',
        description: 'Patch the weakest ally.',
        power: -30,
        target: 'ally-weakest',
      },
      {
        id: 'lasso-snag',
        name: 'Lasso Snag',
        description: 'Damage and trigger Horse Panic.',
        power: 14,
        target: 'enemy',
        status: 'horse-panic',
        range: 3,
      },
      {
        id: 'tonic-toss',
        name: 'Tonic Toss',
        description: 'Small heal and clears one status.',
        power: -18,
        target: 'ally-weakest',
        cleanse: true,
      },
    ],
    grid: { x: 7, y: 4 },
  },
];

export const horseCatalog = {
  comet: {
    id: 'comet',
    name: 'Comet',
    personality: 'Steady trail horse that calms wounded riders.',
    speed: 1.18,
    guard: 0.9,
    combo: "Dead Man's Charge",
  },
  'brass-hoof': {
    id: 'brass-hoof',
    name: 'Brass Hoof',
    personality: 'Stubborn iron-nerved charger that protects its rider.',
    speed: 0.94,
    guard: 0.72,
    combo: 'Iron Canyon Break',
  },
  'ghost-pepper': {
    id: 'ghost-pepper',
    name: 'Ghost Pepper',
    personality: 'Restless sprint horse that loves reckless openings.',
    speed: 1.34,
    guard: 1.08,
    combo: 'Dust Devil Run',
  },
};

export const riderStances = ['Gunslinger', 'Sharpshooter', 'Wrangler', 'Outlaw', 'Iron Rider'];
export const riderStanceDetails = {
  Gunslinger: 'Fast ATB, strongest from Mid lane, and weaker at long range.',
  Sharpshooter: 'Slower ATB, strongest from Back lane, ridges, and cover.',
  Wrangler: 'Control stance. Repositions cheaply and disrupts mounted enemies.',
  Outlaw: 'Damage rises while wounded, Wanted, or fighting from the Front lane.',
  'Iron Rider': 'Defensive stance. Reduces incoming damage.',
};
export const horseStances = ['Stampede', 'Defensive Guard', 'Sprint', 'Calm Focus', 'Wild Frenzy'];

export const statusEffects = {
  sunstroke: {
    id: 'sunstroke',
    label: 'Sunstroke',
    description: 'Heat attrition. Slower ATB, reduced healing, and weaker aim.',
    negative: true,
  },
  'bleeding-out': {
    id: 'bleeding-out',
    label: 'Bleeding Out',
    description: 'HP drains over time. Acting worsens the wound, but low HP builds ATB faster.',
    negative: true,
  },
  'whiskey-dazed': {
    id: 'whiskey-dazed',
    label: 'Whiskey-Dazed',
    description: 'Takes less damage and crits harder, but aim suffers. Immune to Fear.',
  },
  wanted: {
    id: 'wanted',
    label: 'Wanted',
    description: 'Enemies prioritize this outlaw. Damage dealt and damage taken both rise.',
  },
  'horse-panic': {
    id: 'horse-panic',
    label: 'Horse Panic',
    description: 'Mounted skills disabled. The mount may buck the rider out of position.',
    negative: true,
  },
  'dust-choked': {
    id: 'dust-choked',
    label: 'Dust-Choked',
    description: 'Ranged attacks weaken, charges falter, and damage briefly stalls ATB.',
    negative: true,
  },
  showdown: {
    id: 'showdown',
    label: 'Showdown',
    description: 'Cinematic burst state. Faster ATB, stronger crit pressure, and attacks do not miss.',
  },
  grit: {
    id: 'grit',
    label: 'Grit',
    description: 'Refuses to fall once, gains ATB, and resists interruption.',
  },
  fatigue: {
    id: 'fatigue',
    label: 'Fatigue',
    description: 'Temporary crash after heroic exertion. ATB slows.',
    negative: true,
  },
  guarded: {
    id: 'guarded',
    label: 'Guarded',
    description: 'Incoming damage is reduced.',
  },
  marked: {
    id: 'marked',
    label: 'Marked',
    description: 'Takes increased focused damage.',
    negative: true,
  },
  quick: {
    id: 'quick',
    label: 'Quick',
    description: 'ATB builds faster.',
  },
  snared: {
    id: 'snared',
    label: 'Snared',
    description: 'ATB builds slower.',
    negative: true,
  },
};

export const itemCatalog = {
  bandage: {
    id: 'bandage',
    name: 'Bandage',
    description: 'Heal 18 HP and stop Bleeding Out.',
    heal: 18,
    clears: ['bleeding-out'],
  },
  canteen: {
    id: 'canteen',
    name: 'Canteen',
    description: 'Clear Sunstroke, Dust-Choked, and Fatigue.',
    clears: ['sunstroke', 'dust-choked', 'fatigue'],
  },
  whiskey: {
    id: 'whiskey',
    name: 'Whiskey',
    description: 'Gain Whiskey-Dazed and Wanted.',
    applies: ['whiskey-dazed', 'wanted'],
  },
};

export const bountyContracts = {
  redSashRifleman: {
    id: 'redSashRifleman',
    name: 'The Ridge-Gate Rifleman',
    targetEnemyId: 'rifleman',
    targetName: 'Canyon Rifleman',
    baseReward: 95,
    bonusReward: 35,
    optional: 'Win with every crew member standing.',
    description: 'Bring down the rifleman guarding Cinder Mesa Road.',
  },
};

export const encounters = {
  tutorialDustup: {
    id: 'tutorialDustup',
    name: 'Tutorial Dustup',
    enemies: [
      {
        id: 'raider',
        side: 'enemy',
        name: 'Practice Raider',
        short: 'Raider',
        description: 'A low-pressure outlaw used to teach ATB, targeting, cover, and intent.',
        maxHp: 58,
        hp: 58,
        atb: 0,
        speed: 8,
        statuses: [],
        grid: { x: 1, y: 2 },
      },
      {
        id: 'rifleman',
        side: 'enemy',
        name: 'Practice Rifleman',
        short: 'Rifle',
        description: 'A slow shooter who demonstrates enemy intent and line of fire.',
        maxHp: 46,
        hp: 46,
        atb: 0,
        speed: 7,
        statuses: [],
        grid: { x: 1, y: 4 },
      },
    ],
  },
  redSashAmbush: {
    id: 'redSashAmbush',
    name: 'Red Sash Ambush',
    enemies: [
      {
        id: 'raider',
        side: 'enemy',
        name: 'Red Sash Raider',
        short: 'Raider',
        description: 'A fast outlaw who pressures wounded riders with reckless pistol fire.',
        maxHp: 84,
        hp: 84,
        atb: 18,
        speed: 11,
        statuses: [],
        grid: { x: 0, y: 1 },
      },
      {
        id: 'rifleman',
        side: 'enemy',
        name: 'Canyon Rifleman',
        short: 'Rifle',
        description: 'A patient long gunner who benefits from ridges and punishes exposed targets.',
        maxHp: 70,
        hp: 70,
        atb: 4,
        speed: 13,
        statuses: [],
        grid: { x: 0, y: 2 },
      },
      {
        id: 'bruiser',
        side: 'enemy',
        name: 'Dust Bruiser',
        short: 'Bruiser',
        description: 'A durable brawler who soaks damage and tries to break the party line.',
        maxHp: 99,
        hp: 99,
        atb: 0,
        speed: 9,
        statuses: [],
        grid: { x: 0, y: 3 },
      },
    ],
  },
  ridgeDuel: {
    id: 'ridgeDuel',
    name: 'Ridge-Gate Duel',
    enemies: [
      {
        id: 'rifleman',
        side: 'enemy',
        name: 'Canyon Rifleman',
        short: 'Rifle',
        description: 'A patient long gunner who benefits from ridges and punishes exposed targets.',
        maxHp: 76,
        hp: 76,
        atb: 24,
        speed: 14,
        statuses: [],
        grid: { x: 0, y: 1 },
      },
      {
        id: 'rifleman',
        side: 'enemy',
        name: 'High-Ridge Deadeye',
        short: 'Deadeye',
        description: 'A ridge shooter who forces the crew to break line of sight or rush cover.',
        maxHp: 68,
        hp: 68,
        atb: 36,
        speed: 12,
        statuses: [],
        grid: { x: 1, y: 5 },
      },
      {
        id: 'raider',
        side: 'enemy',
        name: 'Red Sash Spotter',
        short: 'Spotter',
        description: 'A skirmisher who flushes riders out of safe lanes with dust shots.',
        maxHp: 64,
        hp: 64,
        atb: 8,
        speed: 15,
        statuses: [],
        grid: { x: 2, y: 3 },
      },
    ],
  },
  gullyRush: {
    id: 'gullyRush',
    name: 'Gully Rush',
    enemies: [
      {
        id: 'bruiser',
        side: 'enemy',
        name: 'Dust Bruiser',
        short: 'Bruiser',
        description: 'A durable brawler who soaks damage and tries to break the party line.',
        maxHp: 110,
        hp: 110,
        atb: 28,
        speed: 10,
        statuses: [],
        grid: { x: 2, y: 2 },
      },
      {
        id: 'bruiser',
        side: 'enemy',
        name: 'Gully Breaker',
        short: 'Breaker',
        description: 'A close-range brawler who turns poor positioning into Horse Panic.',
        maxHp: 92,
        hp: 92,
        atb: 10,
        speed: 12,
        statuses: [],
        grid: { x: 1, y: 4 },
      },
      {
        id: 'raider',
        side: 'enemy',
        name: 'Red Sash Raider',
        short: 'Raider',
        description: 'A fast outlaw who pressures wounded riders with reckless pistol fire.',
        maxHp: 72,
        hp: 72,
        atb: 38,
        speed: 13,
        statuses: [],
        grid: { x: 0, y: 0 },
      },
    ],
  },
};
