export const terrainTypes = {
  dust: {
    id: 'dust',
    label: 'Dust Flat',
    elevation: 0,
    color: 0xad7536,
    tileFrame: 0,
    movementCost: 1,
    cover: false,
    note: 'Open ground. No elevation modifier.',
  },
  road: {
    id: 'road',
    label: 'Mesa Road',
    elevation: 0,
    color: 0xc58b45,
    tileFrame: 2,
    movementCost: 1,
    cover: false,
    note: 'Open road. Fast and exposed.',
  },
  ridge: {
    id: 'ridge',
    label: 'Ridge +1',
    elevation: 1,
    color: 0x8d5d30,
    tileFrame: 1,
    movementCost: 1,
    cover: false,
    note: 'Higher ground. Sharpshooter attacks gain damage.',
  },
  highRidge: {
    id: 'highRidge',
    label: 'High Ridge +2',
    elevation: 2,
    color: 0x6f4a2d,
    tileFrame: 1,
    movementCost: 2,
    cover: false,
    note: 'Strong high ground. Mounted charge loses accuracy here.',
  },
  gully: {
    id: 'gully',
    label: 'Gully -1',
    elevation: -1,
    color: 0x57351f,
    tileFrame: 0,
    movementCost: 1,
    cover: false,
    note: 'Low ground. Units take more rush damage.',
  },
  cover: {
    id: 'cover',
    label: 'Wagon Cover',
    elevation: 0,
    color: 0x4b3120,
    tileFrame: 7,
    movementCost: 2,
    cover: true,
    note: 'Cover tile. Unmounted riders reduce incoming shots.',
  },
  brokenSign: {
    id: 'brokenSign',
    label: 'Broken Sign',
    elevation: 0,
    color: 0x4b3120,
    tileFrame: 6,
    movementCost: 2,
    cover: true,
    note: 'Cover tile. A busted frontier sign breaks sightlines.',
  },
  barrelCover: {
    id: 'barrelCover',
    label: 'Barrel Cover',
    elevation: 0,
    color: 0x4b3120,
    tileFrame: 8,
    movementCost: 2,
    cover: true,
    note: 'Cover tile. Scattered barrels protect unmounted units.',
  },
  cactusPatch: {
    id: 'cactusPatch',
    label: 'Cactus Patch',
    elevation: 0,
    color: 0x2f6f3f,
    tileFrame: 4,
    movementCost: 2,
    cover: false,
    hazardDamage: 3,
    note: 'Movement hazard. Riders take chip damage when they enter.',
  },
  mud: {
    id: 'mud',
    label: 'Mud Wash',
    elevation: -1,
    color: 0x5a4030,
    tileFrame: 0,
    movementCost: 3,
    cover: false,
    mountedSlow: true,
    note: 'Sticky low ground. Mounted units spend more movement here.',
  },
};

export function getTerrainDefinition(id) {
  return terrainTypes[id] || terrainTypes.dust;
}
