const powerup = 'powerup';
const relic = 'relic';

const makeLevels = (levels) => levels.map((effect, index) => ({ level: index + 1, effect }));

export const RARITY_XP_MULTIPLIER = {
  common: 1,
  uncommon: 1.35,
  rare: 1.8,
  epic: 2.4,
  legendary: 3.25,
  mythic: 4.4,
};

const relicRarity = {
  'sky-vane-rig': 'common',
  'stormglass-battery': 'rare',
  'cinder-fuse': 'common',
  'prism-lens': 'rare',
  'rime-keel': 'common',
  'vinewrapped-cargo-net': 'common',
  'rivet-armor-plate': 'rare',
  'powder-keg-breech': 'rare',
  'temple-aether-chime': 'epic',
  'umbral-gyroscope': 'epic',
  'chainstorm-coil': 'rare',
  'ricochet-chamber': 'rare',
  'gravity-mine': 'rare',
  'harpoon-launcher': 'rare',
  'pulse-dash-core': 'rare',
  'quantum-rudder': 'epic',
  'crystal-conduit': 'legendary',
  'cloudbreaker-ram': 'legendary',
  'lightning-rod-mast': 'rare',
  'ember-engine': 'legendary',
  'leviathan-engine': 'legendary',
  'black-horizon-core': 'legendary',
  'heart-of-the-tempest': 'legendary',
  'dead-captains-wheel': 'legendary',
  'corrupted-relic': 'epic',
  'glass-hull': 'legendary',
  'void-sail': 'legendary',
  'celestial-compass': 'legendary',
  'eclipse-cortex': 'mythic',
};

const powerupRarity = {
  'reinforced-hull-plating': 'common',
  'burst-cylinder': 'common',
  'drift-fins': 'common',
  'salvager-magnet': 'common',
  'scrap-barrier': 'common',
  'gun-drone': 'common',
  'arc-reactor': 'common',
  'repair-drone': 'rare',
  'fortune-engine': 'rare',
  'treasure-compass': 'rare',
  'interceptor-drone': 'rare',
  'storm-core': 'rare',
  'flame-vent': 'common',
};

const withRarity = (item) => ({
  rarity: item.kind === relic ? relicRarity[item.id] : powerupRarity[item.id] ?? 'common',
  ...item,
});

export const ITEM_CATALOG = [
  {
    id: 'sky-vane-rig',
    name: 'Sky Vane Rig',
    kind: relic,
    source: 'Starter Sky Enemy Drop',
    baseEffect: 'Improves light-air turning.',
    palette: ['#2d5d70', '#b9f6d6', '#102536'],
    symbol: 'S',
    levels: makeLevels(['Slightly better turning', 'Less drift loss', 'Higher cruise speed', 'Sharper boost steering', 'Trade winds pull the ship forward']),
  },
  {
    id: 'stormglass-battery',
    name: 'Stormglass Battery',
    kind: relic,
    source: 'Storm Fields Enemy Drop',
    baseEffect: 'Stores storm charge as energy.',
    palette: ['#132b4a', '#8df0ff', '#0b1420'],
    symbol: 'B',
    levels: makeLevels(['Minor passive energy', 'More storm energy', 'Energy cap increased', 'Storm rooms recharge faster', 'Overflow charge accelerates weapons']),
  },
  {
    id: 'cinder-fuse',
    name: 'Cinder Fuse',
    kind: relic,
    source: 'Ash Isles Enemy Drop',
    baseEffect: 'Warms the cannons for faster fire.',
    palette: ['#4d2119', '#ff8738', '#1b100b'],
    symbol: 'F',
    levels: makeLevels(['Slightly faster shots', 'Hotter cannon timing', 'Boost heat feeds weapons', 'Shorter firing delay', 'Cinder pressure vents into extra damage']),
  },
  {
    id: 'prism-lens',
    name: 'Prism Lens',
    kind: relic,
    source: 'Crystal Reefs Enemy Drop',
    baseEffect: 'Focuses cannon light into cleaner hits.',
    palette: ['#244960', '#68ffe0', '#231b45'],
    symbol: 'P',
    levels: makeLevels(['Small damage focus', 'Improved beam clarity', 'Ancient-tech resonance', 'Shots cut cleaner paths', 'Prism focus boosts all damage']),
  },
  {
    id: 'rime-keel',
    name: 'Rime Keel',
    kind: relic,
    source: 'Frozen Heights Enemy Drop',
    baseEffect: 'Steadies the ship over frozen currents.',
    palette: ['#38596c', '#d9fbff', '#15212a'],
    symbol: 'I',
    levels: makeLevels(['Reduced drift', 'Better low-speed control', 'Higher ice-lane speed', 'Incoming damage softened', 'Frost wake stabilizes hard turns']),
  },
  {
    id: 'vinewrapped-cargo-net',
    name: 'Vinewrapped Cargo Net',
    kind: relic,
    source: 'Jungle Islands Enemy Drop',
    baseEffect: 'Catches more salvage from wreckage.',
    palette: ['#31583a', '#a5ee8a', '#142418'],
    symbol: 'N',
    levels: makeLevels(['Slightly better loot', 'Wider salvage sweep', 'More XP from kills', 'Better power-up odds', 'Living vines pull valuables closer']),
  },
  {
    id: 'rivet-armor-plate',
    name: 'Rivet Armor Plate',
    kind: relic,
    source: 'Industrial Ruins Enemy Drop',
    baseEffect: 'Bolts extra armor onto the hull.',
    palette: ['#5f686f', '#d6b15f', '#23282c'],
    symbol: 'A',
    levels: makeLevels(['Extra hull', 'Incoming damage reduced', 'Ramming damage improved', 'Armor scales with level', 'Rivets absorb heavy impacts']),
  },
  {
    id: 'powder-keg-breech',
    name: 'Powder-Keg Breech',
    kind: relic,
    source: 'Pirate Dens Enemy Drop',
    baseEffect: 'Loads riskier powder into shots.',
    palette: ['#533624', '#ffb44a', '#1e1712'],
    symbol: 'K',
    levels: makeLevels(['Slight damage boost', 'Faster muzzle pressure', 'Better close-range hits', 'Low-health damage improves', 'Powder bursts splash nearby enemies']),
  },
  {
    id: 'temple-aether-chime',
    name: 'Temple Aether Chime',
    kind: relic,
    source: 'Floating Temples Enemy Drop',
    baseEffect: 'Tunes the engine to ancient currents.',
    palette: ['#26345a', '#f3df85', '#11182b'],
    symbol: 'T',
    levels: makeLevels(['Small energy and turn bonus', 'Ancient-tech resonance', 'Better boost tuning', 'Passive repair pulse', 'Aether tones empower relic systems']),
  },
  {
    id: 'umbral-gyroscope',
    name: 'Umbral Gyroscope',
    kind: relic,
    source: 'Black Cloud Enemy Drop',
    baseEffect: 'Balances the ship inside corrupt turbulence.',
    palette: ['#11101f', '#9d4d75', '#06050a'],
    symbol: 'G',
    levels: makeLevels(['Better dark-cloud control', 'Enemy fire softened', 'Corruption feeds energy', 'Boost and fire timing improve', 'Umbral balance resists battle saturation']),
  },
  {
    id: 'reinforced-hull-plating',
    name: 'Reinforced Hull Plating',
    kind: powerup,
    source: 'Combat Drop',
    baseEffect: 'Increase max HP.',
    durationMs: 60000,
    palette: ['#6f7882', '#c09a55', '#2a3036'],
    symbol: 'H',
    variants: ['Common: +10 temporary max HP', 'Rare: +25 temporary max HP', 'Epic: +40 temporary max HP and impact resistance'],
  },
  {
    id: 'burst-cylinder',
    name: 'Burst Cylinder',
    kind: powerup,
    source: 'Combat Drop',
    baseEffect: 'Weapons fire rapid bursts.',
    durationMs: 30000,
    palette: ['#9b5c32', '#ffb44a', '#2c1911'],
    symbol: 'B',
    variants: ['Common: short burst fire', 'Rare: tighter explosive bursts', 'Epic: cataclysm burst rounds'],
  },
  {
    id: 'drift-fins',
    name: 'Drift Fins',
    kind: powerup,
    source: 'Combat Drop / Frozen Heights Loot',
    baseEffect: 'Improved drifting and turning.',
    durationMs: 35000,
    palette: ['#7ba8b8', '#e7f5ff', '#334b56'],
    symbol: 'D',
    variants: ['Common: tighter turning', 'Rare: boosted drift handling', 'Epic: phantom drift control'],
  },
  {
    id: 'salvager-magnet',
    name: 'Salvager Magnet',
    kind: powerup,
    source: 'Combat Drop',
    baseEffect: 'Increase scrap pickup range and drop rates.',
    durationMs: 90000,
    palette: ['#8c6a3e', '#8fd36a', '#30352b'],
    symbol: 'M',
    variants: ['Common: wider pickup radius', 'Rare: bonus scrap pulls', 'Epic: aggressive loot vacuum'],
  },
  {
    id: 'scrap-barrier',
    name: 'Scrap Barrier',
    kind: powerup,
    source: 'Combat Drop',
    baseEffect: 'Collecting scrap grants temporary armor.',
    durationMs: 50000,
    palette: ['#5f686f', '#d6b15f', '#23282c'],
    symbol: 'S',
    variants: ['Common: temporary armor shield', 'Rare: stronger damage resistance', 'Epic: scrap pickups restore hull'],
  },
  {
    id: 'gun-drone',
    name: 'Gun Drone',
    kind: powerup,
    source: 'Combat Drop',
    baseEffect: 'Combat support drone.',
    durationMs: 75000,
    palette: ['#48525c', '#ffce6a', '#1c2228'],
    symbol: 'G',
    variants: ['Common: basic attack drone', 'Rare: faster support fire', 'Epic: mini-missile support drone'],
  },
  {
    id: 'chainstorm-coil',
    name: 'Chainstorm Coil',
    kind: relic,
    source: 'Elite Reward / Storm Biome Loot',
    baseEffect: 'Lightning chains between enemies.',
    palette: ['#233f5d', '#54e4ff', '#101a2b'],
    symbol: 'C',
    levels: makeLevels(['Chains to 1 enemy', 'Longer chain range', 'Chains to 2 enemies', 'Improved lightning damage', 'Lightning repeatedly chains between enemy groups']),
  },
  {
    id: 'ricochet-chamber',
    name: 'Ricochet Chamber',
    kind: relic,
    source: 'Elite Reward',
    baseEffect: 'Projectiles bounce off terrain.',
    palette: ['#5f5547', '#f1d28a', '#25211d'],
    symbol: 'R',
    levels: makeLevels(['1 bounce', 'Improved bounce consistency', '2 bounces', 'Ricochets deal bonus damage', 'Ricochets slightly seek nearby enemies']),
  },
  {
    id: 'gravity-mine',
    name: 'Gravity Mine',
    kind: relic,
    source: 'Elite Reward',
    baseEffect: 'Deploy gravity trap mines.',
    palette: ['#322047', '#b27bff', '#110d17'],
    symbol: 'V',
    levels: makeLevels(['Small pull radius', 'Longer mine duration', 'Stronger pull effect', 'Enemies slowed after escaping', 'Gravity collapse explosion after expiration']),
  },
  {
    id: 'harpoon-launcher',
    name: 'Harpoon Launcher',
    kind: relic,
    source: 'Elite Reward',
    baseEffect: 'Heavy pulling harpoon weapon.',
    palette: ['#533624', '#c48a4a', '#1e1712'],
    symbol: 'P',
    levels: makeLevels(['Pull small enemies', 'Faster harpoon speed', 'Pull larger enemies slightly', 'Brief stun effect', 'Can grapple terrain and launch the ship']),
  },
  {
    id: 'pulse-dash-core',
    name: 'Pulse Dash Core',
    kind: relic,
    source: 'Elite Reward',
    baseEffect: 'Dash emits damaging shockwave.',
    palette: ['#183d45', '#73f0ff', '#101e22'],
    symbol: 'U',
    levels: makeLevels(['Small shockwave', 'Improved damage', 'Wider shockwave radius', 'Shockwave slows enemies', 'Shockwave creates chain explosions']),
  },
  {
    id: 'arc-reactor',
    name: 'Arc Reactor',
    kind: powerup,
    source: 'Merchant Island',
    baseEffect: 'Increase energy capacity.',
    durationMs: 70000,
    palette: ['#204552', '#81eeff', '#14242a'],
    symbol: 'A',
    variants: ['Common: +10 temporary energy', 'Rare: faster energy regeneration', 'Epic: overcharge at full energy'],
  },
  {
    id: 'repair-drone',
    name: 'Repair Drone',
    kind: powerup,
    source: 'Merchant Island',
    baseEffect: 'Automatic repair support drone.',
    durationMs: 90000,
    palette: ['#31583a', '#a5ee8a', '#142418'],
    symbol: '+',
    variants: ['Common: slow repair beam', 'Rare: combat repair support', 'Epic: emergency burst healing'],
  },
  {
    id: 'fortune-engine',
    name: 'Fortune Engine',
    kind: powerup,
    source: 'Merchant Island',
    baseEffect: 'Higher rarity upgrades appear more often.',
    durationMs: 110000,
    palette: ['#665026', '#ffd66f', '#2c2414'],
    symbol: 'F',
    variants: ['Common: better pickup odds', 'Rare: stronger elite reward odds', 'Epic: legendary route odds increased'],
  },
  {
    id: 'treasure-compass',
    name: 'Treasure Compass',
    kind: powerup,
    source: 'Merchant Island / Exploration Reward',
    baseEffect: 'Reveal hidden loot islands.',
    durationMs: 120000,
    palette: ['#6a5032', '#e5c46b', '#1d1912'],
    symbol: 'T',
    variants: ['Common: reveal nearby loot', 'Rare: reveal elite treasure zones', 'Epic: reveal secret routes'],
  },
  {
    id: 'quantum-rudder',
    name: 'Quantum Rudder',
    kind: relic,
    source: 'Exploration Reward / Secret Discovery',
    baseEffect: 'Teleport dash.',
    palette: ['#26396a', '#80c8ff', '#111828'],
    symbol: 'Q',
    levels: makeLevels(['Short teleport', 'Reduced cooldown', 'Longer teleport distance', 'Teleport damages nearby enemies', 'Temporary invisibility after teleporting']),
  },
  {
    id: 'crystal-conduit',
    name: 'Crystal Conduit',
    kind: relic,
    source: 'Legendary Crystal Reefs Shrine',
    baseEffect: 'Boost all ancient-tech items.',
    palette: ['#244960', '#68ffe0', '#231b45'],
    symbol: 'K',
    levels: makeLevels(['Small ancient-tech bonus', 'Improved relic synergy', 'Ancient-tech cooldown reduction', 'Ancient-tech damage increased', 'Ancient-tech items gain secondary effects']),
  },
  {
    id: 'interceptor-drone',
    name: 'Interceptor Drone',
    kind: powerup,
    source: 'Combat Drop / Exploration Reward',
    baseEffect: 'Destroys incoming projectiles.',
    durationMs: 70000,
    palette: ['#374552', '#b9e7ff', '#171f26'],
    symbol: 'I',
    variants: ['Common: intercepts nearby shots', 'Rare: wider interception field', 'Epic: reflects shots and emits EMP pulses'],
  },
  {
    id: 'cloudbreaker-ram',
    name: 'Cloudbreaker Ram',
    kind: relic,
    source: 'Legendary Starter Sky Shrine',
    baseEffect: 'Destroy environmental obstacles.',
    palette: ['#59412e', '#e0ad6b', '#201712'],
    symbol: 'W',
    levels: makeLevels(['Break weak obstacles', 'Improved collision damage', 'Destroy armored barriers', 'Boost collisions emit shockwaves', 'Boosting crushes smaller enemies instantly']),
  },
  {
    id: 'storm-core',
    name: 'Storm Core',
    kind: powerup,
    source: 'Combat Drop / Storm Biome Loot',
    baseEffect: 'Generate electricity during storms.',
    durationMs: 65000,
    palette: ['#132b4a', '#42dcff', '#0b1420'],
    symbol: 'O',
    variants: ['Common: storm energy trickle', 'Rare: storm resistance and energy conversion', 'Epic: lightning aura during storms'],
  },
  {
    id: 'lightning-rod-mast',
    name: 'Lightning Rod Mast',
    kind: relic,
    source: 'Storm Biome Loot',
    baseEffect: 'Redirect lightning into enemies.',
    palette: ['#27364d', '#eaf67f', '#111827'],
    symbol: 'L',
    levels: makeLevels(['Occasional redirection', 'Increased lightning capture', 'Lightning chains between enemies', 'Lightning restores energy', 'Nearby storms become weaponized automatically']),
  },
  {
    id: 'flame-vent',
    name: 'Flame Vent',
    kind: powerup,
    source: 'Combat Drop / Ash Isles Loot',
    baseEffect: 'Shots ignite enemies.',
    durationMs: 40000,
    palette: ['#5e2018', '#ff8738', '#1f0f0c'],
    symbol: 'N',
    variants: ['Common: shots ignite enemies', 'Rare: burning spreads nearby', 'Epic: burning enemies explode on death'],
  },
  {
    id: 'ember-engine',
    name: 'Ember Engine',
    kind: relic,
    source: 'Legendary Ash Isles Shrine',
    baseEffect: 'Boost leaves fire trails.',
    palette: ['#4d2119', '#ffb047', '#1b100b'],
    symbol: 'E',
    levels: makeLevels(['Short fire trails', 'Longer duration', 'Fire damage increased', 'Fire trails spread flames', 'Boosting creates volcanic eruptions behind ship']),
  },
  {
    id: 'leviathan-engine',
    name: 'Leviathan Engine',
    kind: relic,
    source: 'Legendary Industrial Ruins Shrine',
    baseEffect: 'Massive heavy-ship transformation.',
    palette: ['#26313a', '#9fb2bd', '#11171b'],
    symbol: 'J',
    levels: makeLevels(['Increased size and HP', 'Improved ramming damage', 'Collision shockwaves', 'Temporary unstoppable state while boosting', 'Crush smaller enemies instantly while boosting']),
  },
  {
    id: 'black-horizon-core',
    name: 'Black Horizon Core',
    kind: relic,
    source: 'Legendary Black Cloud Shrine',
    baseEffect: 'Boosting slows time.',
    palette: ['#0a0912', '#9d4d75', '#24162f'],
    symbol: 'Z',
    levels: makeLevels(['Minor time slowdown', 'Longer duration', 'Faster movement during slowdown', 'Weapon speed increased during slowdown', 'Massive cinematic time dilation effect']),
  },
  {
    id: 'heart-of-the-tempest',
    name: 'Heart of the Tempest',
    kind: relic,
    source: 'Legendary Storm Fields Shrine',
    baseEffect: 'Automatic lightning strikes nearby enemies.',
    palette: ['#192a55', '#f4ec77', '#0e1628'],
    symbol: 'Y',
    levels: makeLevels(['Occasional strikes', 'Faster strike frequency', 'Chain lightning added', 'Storms amplify damage', 'Massive lightning storms during combat']),
  },
  {
    id: 'dead-captains-wheel',
    name: "Dead Captain's Wheel",
    kind: relic,
    source: 'Legendary Frozen Heights Shrine',
    baseEffect: 'Greatly improved steering.',
    palette: ['#463226', '#d9c6a0', '#19120e'],
    symbol: 'D',
    levels: makeLevels(['Better turning', 'Reduced drift slowdown', 'Improved boost handling', 'Ghost afterimages confuse enemies', 'Spectral ghost ship assists occasionally']),
  },
  {
    id: 'corrupted-relic',
    name: 'Corrupted Relic',
    kind: relic,
    source: 'Dark Ritual Event',
    baseEffect: 'Random buffs and debuffs.',
    palette: ['#21112e', '#9cff4a', '#08060c'],
    symbol: '?',
    levels: makeLevels(['Minor random effects', 'More positive outcomes', 'Rare massive buffs', 'Reduced debuff duration', 'Can trigger legendary effects randomly']),
  },
  {
    id: 'glass-hull',
    name: 'Glass Hull',
    kind: relic,
    source: 'Legendary Pirate Dens Shrine',
    baseEffect: 'Massive damage boost but fragile defenses.',
    palette: ['#38596c', '#d9fbff', '#15212a'],
    symbol: 'X',
    levels: makeLevels(['+20% damage, reduced HP', 'Higher damage multiplier', 'Critical hit bonus', 'Boosting increases damage further', 'Massive low-health damage multiplier']),
  },
  {
    id: 'void-sail',
    name: 'Void Sail',
    kind: relic,
    source: 'Legendary Floating Temples Shrine',
    baseEffect: 'Teleport through clouds.',
    palette: ['#11101f', '#7559d6', '#06050a'],
    symbol: 'V',
    levels: makeLevels(['Short cloud teleport', 'Reduced cooldown', 'Improved teleport range', 'Temporary invulnerability during teleport', 'Teleport leaves dimensional shockwaves']),
  },
  {
    id: 'celestial-compass',
    name: 'Celestial Compass',
    kind: relic,
    source: 'Legendary Jungle Islands Shrine',
    baseEffect: 'Reveal hidden map information.',
    palette: ['#26345a', '#f3df85', '#11182b'],
    symbol: '*',
    levels: makeLevels(['Reveal hidden nearby routes', 'Reveal elite encounters', 'Reveal legendary nodes', 'Reveal future route outcomes', 'Nearly complete map foresight']),
  },
  {
    id: 'eclipse-cortex',
    name: 'Eclipse Cortex',
    kind: relic,
    source: 'Mythic Black Cloud Puzzle',
    baseEffect: 'Combat saturation corrupts the whole battle state.',
    palette: ['#090913', '#ff2f7d', '#35d0a8'],
    symbol: 'E',
    levels: makeLevels([
      'Corruption Saturation builds during combat',
      'Saturation grants movement acceleration',
      'Saturation accelerates fire rate and enemy aggression',
      'High saturation bends projectiles and amplifies damage',
      'Maximum saturation destabilizes the entire battle',
    ]),
  },
].map(withRarity);

export const ITEM_BY_ID = Object.fromEntries(ITEM_CATALOG.map((item) => [item.id, item]));

const BASE_XP_BY_LEVEL = [0, 4, 10, 18, 30];

export function getXpToNextLevel(item, level) {
  if (item.kind !== relic || level >= 5) return 0;
  return Math.ceil(BASE_XP_BY_LEVEL[level] * RARITY_XP_MULTIPLIER[item.rarity]);
}

export function createRunInventory() {
  return [];
}

export function isXpRelic(item) {
  return item.kind === relic;
}
