export const BIOME_MAPS = [
  {
    id: 'starter-sky',
    name: 'Starter Sky Region',
    mood: 'Adventure and optimism',
    palette: {
      sky: '#5fadd3',
      cloud: '#fff3cf',
      frame: '#6d5534',
      accent: '#d8aa52',
    },
    factions: ['Salvagers', 'Sky Pirates'],
    hazards: ['light turbulence', 'floating debris'],
    encounters: [
      { name: 'Merchant Drift', color: '#d7aa54' },
      { name: 'Pirate Skiff', color: '#aa2f38' },
      { name: 'Salvage Cache', color: '#77985c' },
      { name: 'Storm Bird', color: '#52bdd8' },
    ],
    layout: [
      '..................',
      '.....CCC..........',
      '....CIIIC.....S...',
      '..S.CIFRIC........',
      '....CIIIC.........',
      '.....CCC....R.....',
      '...........RIR....',
      '...S.......III....',
      '...........CIC....',
      '.....RR...........',
      '....RIR.....S.....',
      '..................',
    ],
  },
  {
    id: 'storm-fields',
    name: 'Storm Fields',
    mood: 'Danger and instability',
    palette: {
      sky: '#132033',
      cloud: '#5b6474',
      frame: '#233341',
      accent: '#33d7ff',
    },
    factions: ['Stormrunners', 'Automaton Remnants'],
    hazards: ['lightning storms', 'turbulence', 'cloud anomalies'],
    encounters: [
      { name: 'Lightning Cell', color: '#39d8ff' },
      { name: 'Automaton Drone', color: '#42c6b8' },
      { name: 'Storm Ray', color: '#7288a6' },
      { name: 'Elite Tempest', color: '#f7f3af' },
    ],
    layout: [
      '......S.....L.....',
      '...L.....S........',
      '.......CCC........',
      '..S...CIIIC...L...',
      '......CILIC.......',
      '...L..CIIIC..S....',
      '.......CCC........',
      '............L.....',
      '..S....MMM........',
      '......MIMIM...S...',
      '...L...MMM........',
      '..................',
    ],
  },
  {
    id: 'ash-isles',
    name: 'Ash Isles',
    mood: 'Hostile and unstable',
    palette: {
      sky: '#24191a',
      cloud: '#6d342b',
      frame: '#2c2323',
      accent: '#ff7a2c',
    },
    factions: ['Sky Pirates', 'Salvagers'],
    hazards: ['volcanic eruptions', 'falling debris', 'ember storms'],
    encounters: [
      { name: 'Ash Raider', color: '#b3312b' },
      { name: 'Volcanic Vent', color: '#ff6b26' },
      { name: 'Burnt Wreck', color: '#7c6b62' },
      { name: 'Elite Cinderlord', color: '#ffb347' },
    ],
    layout: [
      '..................',
      '....A.....S.......',
      '...AVA.......P....',
      '..AVIVA.....PIP...',
      '...AVA.......P....',
      '....A.............',
      '..........VVV.....',
      '...S.....VIIV.....',
      '.........VAV......',
      '.....PPP..........',
      '....PIPIP....A....',
      '..................',
    ],
  },
  {
    id: 'crystal-reefs',
    name: 'Crystal Reefs',
    mood: 'Alien and mysterious',
    palette: {
      sky: '#193246',
      cloud: '#52f0e0',
      frame: '#25364f',
      accent: '#a36cff',
    },
    factions: ['Cloud Cultists', 'Automaton Remnants'],
    hazards: ['crystal refraction', 'energy anomalies'],
    encounters: [
      { name: 'Crystal Vault', color: '#74f7de' },
      { name: 'Cult Relicship', color: '#f4da87' },
      { name: 'Sky Jellyfish', color: '#b57cff' },
      { name: 'Ancient Prism', color: '#44d6ff' },
    ],
    layout: [
      '........K.........',
      '.....KKKKK........',
      '....KIIIK.....K...',
      '...KIITIIK..KKK...',
      '....KIIIK.........',
      '.....KKK....S.....',
      '..K.........KKK...',
      '.KKK.......KIITK..',
      '..K.........KKK...',
      '......T...........',
      '.....TIT....K.....',
      '..................',
    ],
  },
  {
    id: 'frozen-heights',
    name: 'Frozen Heights',
    mood: 'Isolation and harsh survival',
    palette: {
      sky: '#9bc8df',
      cloud: '#f5fbff',
      frame: '#6e8795',
      accent: '#c9eef8',
    },
    factions: ['Imperial Fleet', 'Salvagers'],
    hazards: ['snowstorms', 'ice shear', 'thin air'],
    encounters: [
      { name: 'Imperial Patrol', color: '#dfe7ef' },
      { name: 'Frozen Cache', color: '#9ed4e5' },
      { name: 'Cloud Serpent', color: '#bfd7df' },
      { name: 'Elite Icebreaker', color: '#6788a0' },
    ],
    layout: [
      '.....X............',
      '....XXX.....S.....',
      '...XXIXX..........',
      '....XIX....XXX....',
      '.....X....XXIXX...',
      '..........XXXXX...',
      '....S.......X.....',
      '......MMM.........',
      '.....MIXIM........',
      '......MMM.....S...',
      '...X..............',
      '..................',
    ],
  },
  {
    id: 'jungle-islands',
    name: 'Jungle Islands',
    mood: 'Wild, dense, and alive',
    palette: {
      sky: '#4f9fc4',
      cloud: '#e7f3d4',
      frame: '#35523f',
      accent: '#99c45f',
    },
    factions: ['Sky Wildlife', 'Salvagers'],
    hazards: ['thick canopy', 'predators', 'spore clouds'],
    encounters: [
      { name: 'Storm Bird Nest', color: '#5ca75a' },
      { name: 'Jungle Wreck', color: '#9a7148' },
      { name: 'Cloud Serpent', color: '#78cbd7' },
      { name: 'Elite Broodmother', color: '#c9e870' },
    ],
    layout: [
      '..................',
      '...FFF.......S....',
      '..FFIFF...........',
      '..FIIRF....FFF....',
      '..FFIFF...FFIFF...',
      '...FFF....FIFF....',
      '..........FFF.....',
      '.....RR...........',
      '....RIR.....S.....',
      '.....R......FFF...',
      '...........FFIFF..',
      '..................',
    ],
  },
  {
    id: 'industrial-ruins',
    name: 'Industrial Ruins',
    mood: 'Worn machines and buried danger',
    palette: {
      sky: '#536977',
      cloud: '#c6bd9f',
      frame: '#3f3b35',
      accent: '#ba8e46',
    },
    factions: ['Automaton Remnants', 'Imperial Fleet'],
    hazards: ['moving machinery', 'minefields', 'steam vents'],
    encounters: [
      { name: 'Defense Grid', color: '#46d3c6' },
      { name: 'Imperial Claim Team', color: '#dce2e8' },
      { name: 'Gear Vault', color: '#bf8946' },
      { name: 'Elite Foundry Core', color: '#ff8e3c' },
    ],
    layout: [
      '....MMM...........',
      '...MIIIM....S.....',
      '...MIRIM..........',
      '....MMM.....MMM...',
      '............MIM...',
      '...S....RRR.MIM...',
      '.......RIIIRMMM...',
      '........RRR.......',
      '....MMM...........',
      '...MIMIM....S.....',
      '....MMM...........',
      '..................',
    ],
  },
  {
    id: 'pirate-dens',
    name: 'Pirate Dens',
    mood: 'Aggressive, patched, and dangerous',
    palette: {
      sky: '#2f4354',
      cloud: '#a59b88',
      frame: '#372b24',
      accent: '#b8343f',
    },
    factions: ['Sky Pirates'],
    hazards: ['minefields', 'chain gates', 'ambush routes'],
    encounters: [
      { name: 'Raider Dock', color: '#b8323a' },
      { name: 'Cannon Nest', color: '#8d6240' },
      { name: 'Loot Vault', color: '#d0a64c' },
      { name: 'Elite Dread Captain', color: '#f05b63' },
    ],
    layout: [
      '..................',
      '..P....S.....P....',
      '.PIP........PIP...',
      '..P....PPP....P...',
      '......PIIIP.......',
      '......PIRIP.......',
      '..S...PIIIP...S...',
      '.......PPP........',
      '....RR.....RR.....',
      '...RIR....RIR.....',
      '..................',
      '..................',
    ],
  },
  {
    id: 'floating-temples',
    name: 'Floating Temples',
    mood: 'Sacred, ancient, and uncanny',
    palette: {
      sky: '#475d76',
      cloud: '#e8dcc0',
      frame: '#65563c',
      accent: '#66f2ff',
    },
    factions: ['Cloud Cultists', 'Automaton Remnants'],
    hazards: ['relic beams', 'ritual storms', 'collapsing bridges'],
    encounters: [
      { name: 'Cloud Shrine', color: '#f0d77d' },
      { name: 'Cult Procession', color: '#f4f1de' },
      { name: 'Ancient Sentinel', color: '#48d8ce' },
      { name: 'Elite Relic Choir', color: '#75eaff' },
    ],
    layout: [
      '.........T........',
      '........TTT.......',
      '.......TIIIT......',
      '......TIILITT.....',
      '.......TIIIT......',
      '........TTT.......',
      '...S.....T.....S..',
      '.....KK.....KK....',
      '....KITK...KTIK...',
      '.....KK.....KK....',
      '.........T........',
      '..................',
    ],
  },
  {
    id: 'black-cloud-region',
    name: 'Black Cloud Region',
    mood: 'Late-game dread',
    palette: {
      sky: '#090913',
      cloud: '#2a2037',
      frame: '#1c1625',
      accent: '#a72f4d',
    },
    factions: ['Cloud Cultists', 'Automaton Remnants', 'Sky Pirates'],
    hazards: ['dark turbulence', 'corruption anomalies', 'ancient superweapons'],
    encounters: [
      { name: 'Blackstorm Gate', color: '#8a2b53' },
      { name: 'Corrupted Machine', color: '#35d0a8' },
      { name: 'Dread Pirate Wing', color: '#c23b45' },
      { name: 'Boss Fortress', color: '#ed5a72' },
    ],
    layout: [
      '..................',
      '.....B.......S....',
      '....BBB...........',
      '...BBIBB....BBB...',
      '....BLB....BBIBB..',
      '.....B......BBB...',
      '........S.........',
      '..BBB.......KKK...',
      '.BBIBB.....KIBK...',
      '..BBB.......KKK...',
      '......B...........',
      '..................',
    ],
  },
];
